# build
plugins:
  - jekyll-paginate
permalink: pretty
collections_dir: collections
markdown: kramdown

# site
title: bartwolff.com
author: Bart Wolff
description: Personal homepage.

# blog
paginate: 7
paginate_path: "/blog/page:num/"

# formats
formats:
  date_only: "%Y-%m-%d"
